version: '3.8'

services:
  app:
    image: jdarc3/data-reader:latest
    ports:
      - "8080:80"
      - "8081:443"
    environment:
      - MongoConnection:ConnectionString=mongodb://root:example@mongo:27017/
      - MongoConnection:DatabaseName=Parameters
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app_db
  scrapy:
    image: jdarc3/game-finder:latest
    ports:
      - "8083:80"

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - app_db
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

networks:
  app_db:
